# This an example configuration file for next bus bot cli

[cli]
# output formatting option, default are False.

pretty = true
compact = true
verbose = false

[stop.places]
# Zone de correspondance reference:
# https://data.iledefrance-mobilites.fr/explore/dataset/zones-de-correspondance/custom/?disjunctive.zdctype
#
# C01561 is the bus line "9" on the Plateau de Saclay.
# C01567 is the bus line "Express 91-06" on the plateau de Saclay.
#
# The name of the step as a key does not matter,
# it should only be consistent between the stops, stops.aliases and stop.directions sections.
#
# The first stop defined is the default one.
#
"Mare du Vivier" = 420704
"Moulon" =  63086
"Raoul Dautry" = 63236
"Place Marguerite Perey" = 63144

[stop.aliases]
#
"Mare du Vivier" = ["CEA Porte Sud", "Neurospin", "nsp", "mdv"]
"Moulon" = ["ens"]
"Raoul Dautry" = ["CEA Porte Est"]
"Place Marguerite Perey" = ["Inria"]

[stop.direction_filter]

# For each stop you can filter direction, either by specifying a IDFM stop_area code, or the commercial name.

"Mare du Vivier" = ["Gare du Guichet", "Centre Commercial Ulis 2"]      # Only keep the gare du guichet  and Centre commercial ulis2
"Moulon" = ["Gare du Guichet", "Centre Commercial Ulis 2"]      # Only keep the gare du guichet  and Centre commercial ulis2
#"Mare du Vivier" = ["Gare du Guichet", "60998", "!Christ de Saclay"]  # Filter Christ de Saclay direction out
